# Adam Forestier
## Last Updated: September 19, 2023

This File covers the following:
- Exercises related to the lessons contained in Tensorflow_Fundamentals.ipynb

In [4]:
import numpy as np
import pandas as pd
import tensorflow as tf

**Exercises**
1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant().
2. Find the shape, rank and size of the tensors you created in 1.
3. Create two tensors containing random values between 0 and 1 with shape [5, 300].
4. Multiply the two tensors you created in 3 using matrix multiplication.
5. Multiply the two tensors you created in 3 using dot product.
6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].
7. Find the min and max values of the tensor you created in 6 along the first axis.
8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].
9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.
10. One-hot encode the tensor you created in 9.

In [5]:
#1.
s = tf.constant(7)
v = tf.constant([1, 2, 3])
M = tf.constant([[1, 2, 3],
                 [4, 5, 6]])
T = tf.constant([[[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]],
                 [[10, 11, 12],
                  [13, 14, 15],
                  [16, 17, 18]]])
T

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [8]:
#2.
tensors = [s, v, M, T]
for t in tensors:
  print(f'Shape: {t.shape}')
  print(f'Rank: {t.ndim}')
  print(f'Size: {tf.size(t).numpy()}\n')

Shape: ()
Rank: 0
Size: 1

Shape: (3,)
Rank: 1
Size: 3

Shape: (2, 3)
Rank: 2
Size: 6

Shape: (2, 3, 3)
Rank: 3
Size: 18



In [11]:
#3.
T1 = tf.constant(np.random.randint(low=5, high=300, size=(5, 300)))
T2 = tf.constant(np.random.randint(low=5, high=300, size=(5, 300)))

In [12]:
#4.
tf.linalg.matmul(a=T1, b=T2, transpose_a=True)

<tf.Tensor: shape=(300, 300), dtype=int64, numpy=
array([[ 71617,  82851,  63678, ...,  59523, 100834,  89645],
       [122742, 145902,  80761, ..., 100117, 137800, 147296],
       [139881, 164461, 108000, ..., 134672, 164589, 149242],
       ...,
       [ 87271, 108705,  56764, ...,  69449, 111050, 107459],
       [132190, 124286,  90203, ...,  97671, 120489, 148151],
       [145661, 119429, 135707, ..., 122645, 143880, 151813]])>

In [13]:
#5.
T1 @ tf.reshape(tensor=T2, shape=(300,5))

<tf.Tensor: shape=(5, 5), dtype=int64, numpy=
array([[6849523, 7065100, 7437786, 7122431, 7734930],
       [6410871, 6999086, 6963534, 7230303, 7564830],
       [6571793, 6735925, 7094243, 6984094, 7411396],
       [6547281, 6507171, 6858012, 6816130, 7236817],
       [7116885, 6834302, 7378120, 7315936, 7590128]])>

In [26]:
#6.
T = tf.random.uniform(shape=(224, 224, 3), minval=0, maxval=1)

In [33]:
# 7.
print(f'Min along 1st axis: {tf.math.reduce_min(input_tensor=T[0])}')
print(f'Max along 1st axis: {tf.math.reduce_max(input_tensor=T[1])}')

Min along 1st axis: 0.00015616416931152344
Max along 1st axis: 0.9999549388885498


In [25]:
#8.
rg = tf.random.Generator.from_seed(42)
T = rg.normal(shape=(1, 224, 224, 3))
Sqz_T = tf.squeeze(input=T)
Sqz_T.shape

TensorShape([224, 224, 3])

In [17]:
#9.
T = tf.constant(value=np.random.randint(low=1, high=10, size=10), shape=(10))
i_max = tf.math.argmax(input=T)
i_max

<tf.Tensor: shape=(), dtype=int64, numpy=3>

In [20]:
#10.
hot = tf.one_hot(indices=T, depth=10)
hot

<tf.Tensor: shape=(10, 10), dtype=float32, numpy=
array([[0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.]], dtype=float32)>