# Fundamental Concepts of tensors using Tensorflow
* Introduction to Tensors
* Getting information from tensors
* Manipulating tensors
* Tensors & NumPy
* Using @tf.function (a way to speed up regular python functions)
* Using GPUs or TPUs with Tensorflow

In [1]:
# Import Tensorflow
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.17.0


### Creating with tf.constant

In [2]:
# Creating tensors with tf.constant()
scalar = tf.constant(7)
scalar

<tf.Tensor: shape=(), dtype=int32, numpy=7>

In [3]:
# Check number of dimensions of tensor
scalar.ndim

0

In [4]:
# Create a vector
vector = tf.constant([10,10])
vector

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([10, 10], dtype=int32)>

In [5]:
# Check vector dimensions
vector.ndim

1

In [6]:
# Create a matrix
matrix = tf.constant([[10,7],[7,10]])
matrix

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[10,  7],
       [ 7, 10]], dtype=int32)>

In [7]:
# Check matrix dimensions
matrix.ndim

2

In [8]:
# Create a matrix of floats
matrix_float = tf.constant([[10.,7.]
                            ,[7.,10.],
                            [3., 2.]], dtype=tf.float16)
matrix_float

<tf.Tensor: shape=(3, 2), dtype=float16, numpy=
array([[10.,  7.],
       [ 7., 10.],
       [ 3.,  2.]], dtype=float16)>

In [9]:
# Number of dimensions of matrix float
matrix_float.ndim


2

In [10]:
# Create a tensor. a 3d matrx
tensor = tf.constant([[[1, 2, 3],
                       [4, 5, 6]],
                      [[10, 11, 12],
                       [11, 11, 11]],
                      [[111, 99, 23],
                       [23, 22, 112]]])
tensor

<tf.Tensor: shape=(3, 2, 3), dtype=int32, numpy=
array([[[  1,   2,   3],
        [  4,   5,   6]],

       [[ 10,  11,  12],
        [ 11,  11,  11]],

       [[111,  99,  23],
        [ 23,  22, 112]]], dtype=int32)>

In [11]:
# Tensor dimensions
tensor.ndim

3

### Creating with tf.Variable

In [12]:
# Create same tensor as 'tensor' with .Variable
mutable_tensor = tf.Variable([10, 7])
immutable_tensor = tf.constant([10, 7])
mutable_tensor, immutable_tensor

(<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([10,  7], dtype=int32)>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([10,  7], dtype=int32)>)

In [13]:
# Let's change element
mutable_tensor[0].assign(7)
mutable_tensor

<tf.Variable 'Variable:0' shape=(2,) dtype=int32, numpy=array([7, 7], dtype=int32)>

### Creating Random Tensors

In [14]:
# matrix of random values
random_1 = tf.random.Generator.from_seed(42)
random_1 = random_1.normal(shape=(3,2))
random_1

<tf.Tensor: shape=(3, 2), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702],
       [ 0.07595026, -1.2573844 ],
       [-0.23193763, -1.8107855 ]], dtype=float32)>

In [15]:
# Tensor0 of random values
random_2 = tf.random.Generator.from_seed(42)
random_2 = random_2.normal(shape=(3,3))
random_2

<tf.Tensor: shape=(3, 3), dtype=float32, numpy=
array([[-0.7565803 , -0.06854702,  0.07595026],
       [-1.2573844 , -0.23193763, -1.8107855 ],
       [ 0.09988727, -0.50998646, -0.7535805 ]], dtype=float32)>

### Shuffle Random Tensors

In [16]:
not_shuffled = tf.constant([[10, 7],
                            [3, 4],
                            [2, 5]])
not_shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

In [17]:
# Shuffle
tf.random.set_seed(42)
shuffled = tf.random.shuffle(value=not_shuffled, seed=42)
shuffled

<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
array([[10,  7],
       [ 3,  4],
       [ 2,  5]], dtype=int32)>

### Creating tensors from numpy arrays
The main difference between NumPy arrays and Tensorflow Tensors, is that Tensors can be run on a gpu (Faster)


In [18]:
# All ones, pass in shape
tf.ones([10,7])

<tf.Tensor: shape=(10, 7), dtype=float32, numpy=
array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]], dtype=float32)>

In [19]:
# NP Array
numpy_A = np.arange(1, 25, dtype=np.int32)
numpy_A

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24], dtype=int32)

In [20]:
# Turn into tensor
A = tf.constant(numpy_A)

# Turn into 3d tensor
B = tf.constant(numpy_A, shape=(2, 3, 4))
A, B

(<tf.Tensor: shape=(24,), dtype=int32, numpy=
 array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23, 24], dtype=int32)>,
 <tf.Tensor: shape=(2, 3, 4), dtype=int32, numpy=
 array([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12]],
 
        [[13, 14, 15, 16],
         [17, 18, 19, 20],
         [21, 22, 23, 24]]], dtype=int32)>)

### Tensor Attributes
* Shape
* Rank
* Axis or dimension
* Size

In [21]:
B.shape

TensorShape([2, 3, 4])

In [22]:
B.ndim

3

In [23]:
tf.size(B)

<tf.Tensor: shape=(), dtype=int32, numpy=24>

In [24]:
rank_4_tensor = tf.zeros(shape=[2,3,4,5])
rank_4_tensor

<tf.Tensor: shape=(2, 3, 4, 5), dtype=float32, numpy=
array([[[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]],


       [[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]],

        [[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]]], dtype=float32)>

In [25]:
rank_4_tensor[0]

<tf.Tensor: shape=(3, 4, 5), dtype=float32, numpy=
array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]], dtype=float32)>

In [26]:
rank_4_tensor.shape, rank_4_tensor.ndim, tf.size(rank_4_tensor)

(TensorShape([2, 3, 4, 5]), 4, <tf.Tensor: shape=(), dtype=int32, numpy=120>)

In [27]:
rank_4_tensor.dtype

tf.float32

### Indexing and Expanding Tensors
Indexed just like python lists

*   List item
*   List item



In [28]:
# Get first 2 of each dimension
rank_4_tensor[:2, :2, :2, :2]

<tf.Tensor: shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]],


       [[[0., 0.],
         [0., 0.]],

        [[0., 0.],
         [0., 0.]]]], dtype=float32)>

In [29]:
# Get first element from each dimension from each index except final 1
rank_4_tensor[:1, :1, :1]

<tf.Tensor: shape=(1, 1, 1, 5), dtype=float32, numpy=array([[[[0., 0., 0., 0., 0.]]]], dtype=float32)>

In [30]:
# Create rank 2 tensor
rank_2_tensor = tf.constant([[10, 7],
                              [3, 4]])
rank_2_tensor.shape, rank_2_tensor.ndim

(TensorShape([2, 2]), 2)

In [31]:
# Get last item
rank_2_tensor[:, -1]

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([7, 4], dtype=int32)>

In [32]:
# Add extra dimension
rank_3_tensor = rank_2_tensor[..., tf.newaxis]
rank_3_tensor

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [33]:
# Another way to add dimension
tf.expand_dims(rank_2_tensor, axis=-1)

<tf.Tensor: shape=(2, 2, 1), dtype=int32, numpy=
array([[[10],
        [ 7]],

       [[ 3],
        [ 4]]], dtype=int32)>

In [34]:
# Put dimension at the front instead
tf.expand_dims(rank_2_tensor, axis=0)

<tf.Tensor: shape=(1, 2, 2), dtype=int32, numpy=
array([[[10,  7],
        [ 3,  4]]], dtype=int32)>

### Tensor Operations

In [35]:
# Addition
tensor = tf.constant([[10, 7], [3, 4]])
tensor + 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[20, 17],
       [13, 14]], dtype=int32)>

In [36]:
# Multiplication
tensor * 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

In [37]:
# Subtraction
tensor - 10

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[ 0, -3],
       [-7, -6]], dtype=int32)>

In [38]:
# Use built in function - IT IS FASTER TO USE BUILT IN!
tf.multiply(tensor, 10)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  70],
       [ 30,  40]], dtype=int32)>

### Matrix Multiplication

In ML, matrix multiplication is one of the most common operations.

2 rules matrices need to fulfill to perform matrix multiplcation
1. Inner dimmensions must match
2. The resulting matrix has the shape of the outer dimensions

**KEY** - When needing to line up shape of tensors to get dot product, generally, do *tf.transpose*, not *tf.reshape*

In [39]:
# Matrix multiplication in tensorflow tf.linalg.matmul (dot product)
tf.matmul(tensor, tensor)

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[121,  98],
       [ 42,  37]], dtype=int32)>

In [40]:
# not dot product, just element by element
tensor * tensor

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[100,  49],
       [  9,  16]], dtype=int32)>

In [41]:
# 3 by 2
tensor_B = tf.constant([[10, 3],
                      [3, 4],
                      [2, 5]])
tensor_C = tf.constant([[3, 5],
                        [6, 7],
                        [1, 8]])
tensor_B, tensor_C

(<tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[10,  3],
        [ 3,  4],
        [ 2,  5]], dtype=int32)>,
 <tf.Tensor: shape=(3, 2), dtype=int32, numpy=
 array([[3, 5],
        [6, 7],
        [1, 8]], dtype=int32)>)

In [42]:
#  tf.matmul(tensor_B, tensor_C) - imcompatable

In [43]:
# Must have same inner dimension
tensor_C = tf.reshape(tensor_C, shape=(2, 3))

In [44]:
# Now can matrix multiply (3,2 and 2,3) - same inner dimension (2) new size = 3 x 3
tf.matmul(tensor_B, tensor_C)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[51, 53, 84],
       [37, 19, 50],
       [41, 15, 52]], dtype=int32)>

In [45]:
# Look at transpose - flips tensor on its axis
tf.transpose(tensor_B), tf.reshape(tensor_B, shape=(2, 3))

(<tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[10,  3,  2],
        [ 3,  4,  5]], dtype=int32)>,
 <tf.Tensor: shape=(2, 3), dtype=int32, numpy=
 array([[10,  3,  3],
        [ 4,  2,  5]], dtype=int32)>)

**The dot Product**
Matrix multiplication is also referred to as "dot product"
You can perform using
* tf.matmul()
* tf.tensordot
* tensor @ tensor



In [46]:
# Perform dot prod on X and Y (requires b or c to be transposed)
tf.tensordot(tensor_B, tensor_C, axes=1)

<tf.Tensor: shape=(3, 3), dtype=int32, numpy=
array([[51, 53, 84],
       [37, 19, 50],
       [41, 15, 52]], dtype=int32)>

### Changing datatype of tensors
Default dtype is float32 in tensorflow. float 16 has less precision and runs faster!

In [47]:
B = tf.constant([1.7, 7.4])
B.dtype

tf.float32

In [48]:
# change to 16 bit
B = tf.cast(x=B, dtype=tf.float16)
B

<tf.Tensor: shape=(2,), dtype=float16, numpy=array([1.7, 7.4], dtype=float16)>

### Aggregation

In [55]:
# Get absolute values
D = tf.constant([-7, -10])
tf.abs(D)

<tf.Tensor: shape=(2,), dtype=int32, numpy=array([ 7, 10], dtype=int32)>

In [56]:
E = tf.constant(np.random.randint(0, 100, size=50))
E

<tf.Tensor: shape=(50,), dtype=int64, numpy=
array([88, 72, 77,  2, 21, 17, 95, 49, 89, 39, 26, 89, 78, 42, 62, 95, 48,
       28, 76, 52, 35, 12, 80, 82, 28, 96, 69, 98, 69, 47, 39, 55, 77, 59,
       93, 52, 22, 64, 35, 70, 51, 86, 59, 73, 87, 20, 30, 47, 36, 11])>

In [58]:
# min
tf.reduce_min(E).numpy()

2

In [59]:
# max
tf.reduce_max(E).numpy()

98

In [60]:
# mean
tf.reduce_mean(E).numpy()

56

In [61]:
# sum
tf.reduce_sum(E).numpy()

2827

In [65]:
# Variance
tf.math.reduce_variance(tf.cast(E, dtype=tf.float16)).numpy()

693.0

In [66]:
# standard deviation
tf.math.reduce_std(tf.cast(E, dtype=tf.float16)).numpy()

26.33

### Finding positional min (argmin) and positional max (argmin)

In [71]:
tf.random.set_seed(42)
F = tf.random.uniform(shape=[50], seed=42)
F

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.4163028 , 0.26858163, 0.47968316, 0.36457133, 0.95471144,
       0.9418646 , 0.61483395, 0.35842144, 0.5936024 , 0.21551096,
       0.07745171, 0.57921314, 0.29180396, 0.26718032, 0.37012458,
       0.7161033 , 0.45877767, 0.11764562, 0.21073711, 0.5441973 ,
       0.9898069 , 0.38395858, 0.04683566, 0.8718462 , 0.25881708,
       0.873135  , 0.64698434, 0.41981232, 0.24148273, 0.09550059,
       0.9820819 , 0.1570208 , 0.2997682 , 0.36795306, 0.9453716 ,
       0.11056781, 0.52287626, 0.8305441 , 0.0020721 , 0.9594034 ,
       0.85630023, 0.3944497 , 0.22028875, 0.67066073, 0.01875746,
       0.48057055, 0.5953454 , 0.6847329 , 0.18988943, 0.12489867],
      dtype=float32)>

In [72]:
tf.argmax(F).numpy()

20

In [73]:
tf.argmin(F).numpy()

38

In [74]:
F[20], F[38]

(<tf.Tensor: shape=(), dtype=float32, numpy=0.9898069>,
 <tf.Tensor: shape=(), dtype=float32, numpy=0.0020720959>)

In [75]:
# Get biggest value by indexing on argmax
F[tf.argmax(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.9898069>

In [76]:
# Get smallest value by indexing on argmin
F[tf.argmin(F)]

<tf.Tensor: shape=(), dtype=float32, numpy=0.0020720959>

### Squeezing Tensor (removing all 1-dimension axes)
Removes dimensions of size 1 from the shape of a tensor

In [79]:
tf.random.set_seed(42)
G = tf.constant(tf.random.uniform(shape=[50]), shape=(1, 1, 1, 1, 50))
G

<tf.Tensor: shape=(1, 1, 1, 1, 50), dtype=float32, numpy=
array([[[[[0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
           0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
           0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
           0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
           0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
           0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
           0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
           0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
           0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
           0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043]]]]],
      dtype=float32)>

In [80]:
G_squeezed = tf.squeeze(G)
G_squeezed

<tf.Tensor: shape=(50,), dtype=float32, numpy=
array([0.6645621 , 0.44100678, 0.3528825 , 0.46448255, 0.03366041,
       0.68467236, 0.74011743, 0.8724445 , 0.22632635, 0.22319686,
       0.3103881 , 0.7223358 , 0.13318717, 0.5480639 , 0.5746088 ,
       0.8996835 , 0.00946367, 0.5212307 , 0.6345445 , 0.1993283 ,
       0.72942245, 0.54583454, 0.10756552, 0.6767061 , 0.6602763 ,
       0.33695042, 0.60141766, 0.21062577, 0.8527372 , 0.44062173,
       0.9485276 , 0.23752594, 0.81179297, 0.5263394 , 0.494308  ,
       0.21612847, 0.8457197 , 0.8718841 , 0.3083862 , 0.6868038 ,
       0.23764038, 0.7817228 , 0.9671384 , 0.06870162, 0.79873943,
       0.66028714, 0.5871513 , 0.16461694, 0.7381023 , 0.32054043],
      dtype=float32)>

### One-hot encoding tensors
A one hot encoding is a representation of categorical variables as binary vectors

In [81]:
some_list = [0, 1, 2, 3]
tf.one_hot(some_list, depth=4)

<tf.Tensor: shape=(4, 4), dtype=float32, numpy=
array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]], dtype=float32)>