# Adam Forestier

## Last Updated: August 11, 2023

In [87]:
# Import NumPy as its abbreviation 'np'
import numpy as np
import pandas as pd

In [88]:
# Create a 1-dimensional NumPy array using np.array()
arr1 = np.array([1, 2, 3])

# Create a 2-dimensional NumPy array using np.array()
arr2 = np.array([[1,2,3], [4,5,6]])

# Create a 3-dimensional Numpy array using np.array()
a3 = np.array([[[21, 76, 88],
                [99, 82, 22.2],
                [22.66, 21.4, 9]],
                [[1, 2, 3],
                [33, 1, 23],
                [22, 90, 22]]])

In [89]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
arr1.shape, arr1.ndim, arr1.shape, arr1.dtype, arr1.size, print(type(arr1))

<class 'numpy.ndarray'>


((3,), 1, (3,), dtype('int32'), 3, None)

In [90]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
df = pd.DataFrame(arr2, columns=['A', 'B', 'C'])
df

A  B  C
0  1  2  3
1  4  5  6

In [91]:
# Create an array of shape (10, 2) with only ones
ones = np.ones(shape=(10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [92]:
# Create an array of shape (7, 2, 3) of only zeros
zeros = np.zeros(shape=(7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [93]:
# Create an array within a range of 0 and 100 with step 3
arr = np.arange(0, 100, 3)
arr

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [94]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
arr = np.random.randint(0, 10, size=(7,2))
arr

array([[2, 3],
       [3, 2],
       [9, 2],
       [2, 3],
       [6, 3],
       [8, 0],
       [7, 6]])

In [95]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
arr = np.random.random(size=(3,5))
arr

array([[0.93672999, 0.13752094, 0.34106635, 0.11347352, 0.92469362],
       [0.87733935, 0.25794163, 0.65998405, 0.8172222 , 0.55520081],
       [0.52965058, 0.24185229, 0.09310277, 0.89721576, 0.90041806]])

In [96]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
arr = np.random.randint(low=0, high=10, size=(4,6))
arr

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [97]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
arr = np.random.randint(low=1, high=10, size=(3,7))

# Find the unique numbers in the array you just created
np.unique(arr)

array([1, 2, 3, 4, 5, 7, 9])

In [98]:
# Find the 0'th index of the latest array you created
arr[0]

array([9, 1, 3, 7, 4, 9, 3])

In [99]:
# Get the first 2 rows of latest array you created
arr[:2]

array([[9, 1, 3, 7, 4, 9, 3],
       [5, 3, 7, 5, 9, 7, 2]])

In [100]:
# Get the first 2 values of the first 2 rows of the latest array
arr[:2, :2]

array([[9, 1],
       [5, 3]])

In [101]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
r1 = np.random.randint(low=0, high=10, size=(3,5))
ones = np.ones(shape=(3,5))

In [102]:
# Add arrays
r1 + ones

array([[ 7.,  8.,  3.,  1.,  4.],
       [ 2.,  8.,  4.,  2.,  6.],
       [ 6., 10.,  4.,  6.,  2.]])

In [103]:
# Create another array of ones of shape 5,3
ones_2 = np.ones(shape=(5,3))

In [104]:
# Subtract the new array of ones from the other most recent array
r1 - ones

array([[ 5.,  6.,  1., -1.,  2.],
       [ 0.,  6.,  2.,  0.,  4.],
       [ 4.,  8.,  2.,  4.,  0.]])

In [105]:
# Multiply
r1 * ones

array([[6., 7., 2., 0., 3.],
       [1., 7., 3., 1., 5.],
       [5., 9., 3., 5., 1.]])

In [106]:
# Take the latest array to the power of 2 using '**'
r1 ** 2

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [107]:
# Do the same thing with np.square()
np.square(r1)

array([[36, 49,  4,  0,  9],
       [ 1, 49,  9,  1, 25],
       [25, 81,  9, 25,  1]])

In [108]:
# Find the mean of the latest array using np.mean()
np.mean(r1)

3.8666666666666667

In [109]:
# Find the maximum of the latest array using np.max()
np.max(r1)

9

In [110]:
# Find the minimum of the latest array using np.min()
np.min(r1)

0

In [111]:
# Find the standard deviation of the latest array
np.sqrt(np.var(r1)) # Just the square root of variance
np.std(r1)

2.578543947441829

In [112]:
# Find the variance of the latest array
np.var(r1)

6.648888888888889

In [113]:
# Reshape the latest array to (3, 5, 1)
r1 = r1.reshape((3,5,1))
r1

array([[[6],
        [7],
        [2],
        [0],
        [3]],

       [[1],
        [7],
        [3],
        [1],
        [5]],

       [[5],
        [9],
        [3],
        [5],
        [1]]])

In [114]:
# transpose
t1 = r1.T
t1

array([[[6, 1, 5],
        [7, 7, 9],
        [2, 3, 3],
        [0, 1, 5],
        [3, 5, 1]]])

In [115]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
r1 = np.random.randint(0, 10, size=(3,3))
r2 = np.random.randint(0, 10, size=(3,2))

In [116]:
r1.dot(r2)

array([[ 88, 117],
       [100, 123],
       [ 89, 127]])

In [117]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
r1 = np.random.randint(0,10, size=(4,3))
r2 = np.random.randint(0,10, size=(4,3))

In [118]:
# Perform a dot product on the two newest arrays you created
r2 = r2.T
r1.dot(r2)

array([[ 24, 102,  96,   8],
       [ 16, 114, 106,  63],
       [ 22, 123, 114,  56],
       [  8,  60,  58,   7]])

In [119]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
r1 = np.random.randint(0,10, size=(4,3))
r2 = np.random.randint(0,10, size=(4,3))

In [120]:
# Compare with >
r1 > r2

array([[ True,  True, False],
       [False, False, False],
       [False, False, False],
       [False,  True, False]])

In [121]:
# Compare the two arrays with '>='
r1 >= r2

array([[ True,  True, False],
       [False, False, False],
       [False, False, False],
       [False,  True, False]])

In [122]:
# Find which elements of the first array are greater than 7
r1 > 7

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [123]:
# Equal
r1 == r2

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [124]:
# Sort one of the arrays you just created in ascending order
r1 = np.sort(r1)
r1

array([[6, 6, 7],
       [2, 4, 7],
       [0, 2, 5],
       [2, 2, 4]])

In [125]:
# Sort the indexes of one of the arrays you just created
r2_sorted_i = np.argsort(r2)

In [126]:
# Find the index with the maximum value in one of the arrays you've created
np.argmax(r2)

2

In [127]:
# Find the index with the minimum value in one of the arrays you've created
np.argmin(r2)

0

In [128]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
np.argmax(r2, axis=1)

array([2, 2, 0, 0], dtype=int64)

In [129]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
np.argmax(r2, axis=0)

array([2, 2, 0], dtype=int64)

In [130]:
# Create an array of normally distributed random numbers
np.random.normal(size=(1,4))

array([[ 1.79428084,  0.58068954,  0.29765045, -1.02811577]])

In [131]:
# Create an array with 10 evenly spaced numbers between 1 and 100
np.linspace(start=1, stop=100, num=10)

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])